
export const planetData = [
  {
    name: "Mercury",
    size: 0.4,
    distance: 12,
    speed: 0.04,
    color: 0x8c7853,
    description: "Closest to Sun",
  },
  {
    name: "Venus",
    size: 0.9,
    distance: 18,
    speed: 0.035,
    color: 0xffb649,
    description: "Hottest planet",
  },
  {
    name: "Earth",
    size: 1.0,
    distance: 25,
    speed: 0.03,
    color: 0x6b93d6,
    description: "Our home",
  },
  {
    name: "Mars",
    size: 0.5,
    distance: 35,
    speed: 0.024,
    color: 0xcd5c5c,
    description: "Red planet",
  },
  {
    name: "Jupiter",
    size: 3.0,
    distance: 55,
    speed: 0.013,
    color: 0xd2691e,
    description: "Largest planet",
  },
  {
    name: "Saturn",
    size: 2.5,
    distance: 75,
    speed: 0.009,
    color: 0xf4a460,
    description: "Ring planet",
  },
  {
    name: "Uranus",
    size: 1.8,
    distance: 95,
    speed: 0.006,
    color: 0x4fd0e3,
    description: "Ice giant",
  },
  {
    name: "Neptune",
    size: 1.7,
    distance: 115,
    speed: 0.005,
    color: 0x4169e1,
    description: "Windiest planet",
  },
];
